[tool.black]

[tool.pylint."messages control"]
disable=["import-error"]

[project]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.mypy]
disable_error_code = ["import-untyped"]
